# Generated by Django 3.2 on 2022-06-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('currency', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='MappingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo', models.DecimalField(decimal_places=8, default=0.0, max_digits=11, null=True)),
                ('vol_offset', models.DecimalField(decimal_places=8, default=0.0, max_digits=11, null=True)),
                ('FTX_feed_ticker', models.CharField(blank=True, max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_to_db.currencymodel')),
            ],
            options={
                'verbose_name_plural': 'Mapped Data',
            },
        ),
    ]
