# Generated by Django 3.2 on 2022-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('currency', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('depo', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('vol_offset', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ftx_feed_ticker', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Currency Settings',
            },
        ),
    ]
