# Generated by Django 3.2 on 2022-06-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_to_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappingmodel',
            options={'verbose_name_plural': 'Currency Settings'},
        ),
        migrations.RenameField(
            model_name='mappingmodel',
            old_name='vol_offset',
            new_name='offset',
        ),
        migrations.RemoveField(
            model_name='mappingmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='mappingmodel',
            name='currency',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CurrencyModel',
        ),
    ]
