# Generated by Django 3.2 on 2022-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_to_db', '0002_auto_20220609_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingmodel',
            old_name='FTX_feed_ticker',
            new_name='ftx_feed_ticker',
        ),
        migrations.RemoveField(
            model_name='mappingmodel',
            name='offset',
        ),
        migrations.AddField(
            model_name='mappingmodel',
            name='vol_offset',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='mappingmodel',
            name='depo',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
