# Generated by Django 3.2 on 2022-06-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_to_db', '0003_auto_20220609_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingmodel',
            name='depo',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='mappingmodel',
            name='vol_offset',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
