# Generated by Django 3.2 on 2022-06-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_to_db', '0004_auto_20220609_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingModel',
            new_name='CurrencySettings',
        ),
    ]
